name: (RHIZA) VALIDATE

permissions:
  contents: read

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validation:
    runs-on: ubuntu-latest
    # don't run this in rhiza itself. Rhiza has no template.yml file.
    if: ${{ github.repository != 'jebel-quant/rhiza' }}
    container:
      image: ghcr.io/astral-sh/uv:0.9.27-python3.12-trixie

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Validate Rhiza config
        shell: bash
        run: |
          uvx "rhiza>=0.8.0" validate .
